name: Build and Deploy Docker .NET App to Azure App Service

on:
  push:
    branches:
      - main

env:
  ACR_LOGIN_SERVER: azurecontaineregisterytest.azurecr.io
  IMAGE_NAME: dockerapp
  TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Login to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to ACR 
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} -f DockerApp/Dockerfile DockerApp

      # Push image to ACR
      - name: Push Docker Image
        run: |
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      # Deploy App Service to pull this latest image from ACR
      - name: Update App Service to use new image
        run: |
          az webapp config container set \
            --name dockerdemoapp \
            --resource-group DeleteRG \
            --docker-custom-image-name ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            --docker-registry-server-url https://${{ env.ACR_LOGIN_SERVER }}

      # Restart to pull latest image
      - name: Restart App Service
        run: |
          az webapp restart \
            --name dockerdemoapp \
            --resource-group DeleteRG
